# Generated by Django 2.0.3 on 2018-11-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scooter', '0004_auto_20181108_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('start_point_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_point_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_point_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('end_point_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.Scooter')),
            ],
        ),
    ]
