# Generated by Django 2.0.3 on 2018-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
