# Generated by Django 2.0.3 on 2018-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20181115_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='scooter',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
