# Generated by Django 2.0.3 on 2018-11-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0002_scooter_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='device_code',
            field=models.PositiveIntegerField(default=123456),
            preserve_default=False,
        ),
    ]
