# Generated by Django 2.0.3 on 2018-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0003_scooter_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='device_code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
