# Generated by Django 2.0.3 on 2018-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0004_auto_20181108_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='qr_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
