# Generated by Django 2.0.3 on 2018-11-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0005_scooter_qr_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('battery', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ready'), (2, 'occupied'), (3, 'low_battery'), (4, 'unavailable')])),
            ],
        ),
        migrations.AddField(
            model_name='scooter',
            name='last_announce',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='qr_info',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.Scooter'),
        ),
    ]
