# Generated by Django 2.0.3 on 2018-11-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scooter', '0006_auto_20181115_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('start_point_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_point_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_point_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('end_point_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooter.Scooter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
