# Generated by Django 2.0.3 on 2018-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0007_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='last_announce',
            field=models.DateTimeField(),
        ),
    ]
