# Generated by Django 2.0.3 on 2018-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0008_auto_20181118_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='last_announce',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
