# Generated by Django 2.1.1 on 2019-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0009_auto_20181118_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
