# Generated by Django 2.2 on 2019-05-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0011_auto_20190206_1941'),
        ('scooter', '0005_auto_20190425_1029'),
    ]

    operations = [
    ]
