# Generated by Django 2.2 on 2019-05-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0012_merge_20190516_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='end_acknowledge_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='end ack'),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_acknowledge_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='start ack'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.SmallIntegerField(editable=False, null=True, verbose_name='distance(km)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.FloatField(editable=False, null=True, verbose_name='duration(m)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_point_latitude',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='end Lat'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_point_longitude',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='end Lng'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='scooter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scooter.Scooter'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_point_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, verbose_name='start Lat'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_point_longitude',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=9, verbose_name='start Lng'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
