# Generated by Django 2.0.3 on 2018-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181025_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='hassan', max_length=255),
            preserve_default=False,
        ),
    ]
