# Generated by Django 2.1.1 on 2019-02-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_auto_20190203_1556'),
        ('accounts', '0006_auto_20190203_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tariff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='charging.Tariff'),
        ),
    ]
