# Generated by Django 2.1.1 on 2019-02-03 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
