# Generated by Django 2.1.1 on 2019-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_tariff_per_kilometer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='minimum_credit',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
