# Generated by Django 2.1.1 on 2019-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_tariff_minimum_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='free_kilometers',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='free_minutes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
