# Generated by Django 2.1.3 on 2018-12-07 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.BigIntegerField(null=True)),
                ('ref_id', models.BigIntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'شروع'), (1, 'درخواست نامعتبر'), (2, 'درخواست معتبر'), (3, 'تراکنش ناتمام'), (4, 'تراکنش کامل و تایید نشده'), (5, 'تراکنش موفق'), (6, 'تراکنش تکراری'), (7, 'تراکنش ناموفق')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
