# Generated by Django 2.1.3 on 2018-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recharged',
            field=models.BooleanField(default=False),
        ),
    ]
